#lang racket
(require 2htdp/image)
;1(
(above (beside (rectangle 20 20 "solid" "black")
                 (rectangle 20 20 "solid" "grey"))
         (beside (rectangle 20 20 "solid" "grey")
                 (rectangle 20 20 "solid" "black")) )

;2
(beside (circle 20 "solid" "lightblue")
          (circle 40 "solid" "lightblue")
          (circle 60 "solid" "lightblue") )

;3
(above (beside (triangle 30 "solid" "red")
                 (triangle 30 "solid" "red"))
         (rectangle 60 30 "solid" "black"))

;4
(overlay/align "right" "center"
                 (circle 36 "solid" "white")
                 (circle 40 "solid" "black") )

;5
(overlay/align "center" "top"
          (beside (overlay/align "center" "bottom"
                         (circle 5 "solid" "black")
                         (circle 15 "solid" "white"))
                  (overlay/align "center" "bottom"
                         (circle 5 "solid" "black")
                         (circle 15 "solid" "white")))
  (overlay/align "center" "center"
                 (circle 15 "outline" "red")
                   (circle 60 "solid" "pink") ))

;6
(overlay/align "center" "bottom" (rectangle 13 23 "solid" "brown")
(above (beside/align "bottom"
                         (triangle 35 "solid" "red")
                         (triangle 25 "solid" "red"))
           (rectangle 60 35 "solid" "black")))

;7
(define r 80)
(define (kolo r)
  (if (< r 1)
      (circle 0.5 "outline" "red")
      (overlay/align "center" "center" (circle r "outline" "red")
                                       (kolo(- r 10)))))

;8
(define x 80)
(define (kwadrat x)
  (if (< x 1)
      (circle 0.5 "outline" "red")
      (overlay/align "center" "center" (rectangle x x "outline" "black")
                                       (kwadrat (- x 10)))))
;9
(overlay/align "center" "center"
                 (circle 0.5 "solid" "red")
                 (rectangle 10 10 "solid" "blue")
                 (rectangle 20 20 "solid" "black")
                 (rectangle 30 30 "solid" "blue")
                 (rectangle 40 40 "solid" "black")
                 (rectangle 50 50 "solid" "blue")
                 (rectangle 60 60 "solid" "black")
                 (rectangle 70 70 "solid" "blue")
                 (rectangle 80 80 "solid" "black") )

;10
(overlay/align "center" "center"
                 (circle 0.5 "solid" "red")
                 (circle 10 "solid" "orange")
                 (rectangle 28 28 "solid" "yellow")
                 (circle 25 "solid" "orange")
                 (rectangle 52 52 "solid" "yellow")
                 (circle 38 "solid" "orange")
                 (rectangle 75 75 "solid" "yellow")
                 (circle 52 "solid" "orange")
                 (rectangle 100 100 "solid" "yellow") )

;11
(beside (circle 2 "solid" "red")
          (circle 2 "outline" "red")
          (circle 2 "solid" "red")
          (circle 5 "outline" "red")
          (circle 2 "solid" "red")
          (circle 2 "outline" "red")
          (circle 2 "solid" "red")
          (circle 15 "outline" "red")
          (circle 2 "solid" "red")
          (circle 2 "outline" "red")
          (circle 2 "solid" "red")
          (circle 5 "outline" "red")
          (circle 2 "solid" "red")
          (circle 2 "outline" "red")
          (circle 2 "solid" "red")
          (circle 45 "outline" "red")
          (circle 2 "solid" "red")
          (circle 2 "outline" "red")
          (circle 2 "solid" "red")
          (circle 5 "outline" "red")
          (circle 2 "solid" "red")
          (circle 2 "outline" "red")
          (circle 2 "solid" "red")
          (circle 15 "outline" "red")
          (circle 2 "solid" "red")
          (circle 2 "outline" "red")
          (circle 2 "solid" "red")
          (circle 5 "outline" "red")
          (circle 2 "solid" "red")
          (circle 2 "outline" "red")
          (circle 2 "solid" "red") )

(beside (rectangle 600 10 "solid" "lightgrey")
(beside
   (rectangle 2 10 "solid" "black")
   (rectangle 3 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 8 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 1 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 25 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 3 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 8 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 1 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 60 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 3 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 8 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 1 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 25 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 3 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 8 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 1 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 200 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 3 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 8 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 1 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 25 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 3 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 8 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 1 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 60 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 3 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 8 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 1 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 25 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 3 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 8 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black")
   (rectangle 1 10 "solid" "lightgrey")
   (rectangle 2 10 "solid" "black") ))
